# NUMPY
NumPy (Numerical Python) is a Python library for numerical computations. It provides an efficient array object (ndarray) and tools for mathematical, logical, shape manipulation, and statistical operations.

In [10]:
import numpy as np

In [11]:
arr = np.array([1, 2, 3, 4])
print(arr * 2)   # Vectorized operation → [2 4 6 8]

[2 4 6 8]


### Difference between a Python list and a NumPy array?

| Feature     | List                         | NumPy Array           |
|--------------|------------------------------|------------------------|
| Type         | Can hold different data types | Must hold same data type |
| Speed        | Slower                        | Faster (C-based)        |
| Memory       | More memory                   | Less memory             |
| Operations   | Loop-based                    | Vectorized              |


In [13]:
lst = [1, 2, 3]
arr = np.array([1, 2, 3])

print(lst * 2)  # [1, 2, 3, 1, 2, 3]
print(arr * 2)  # [2 4 6]

[1, 2, 3, 1, 2, 3]
[2 4 6]


### Create NumPy arrays

In [17]:
a = np.array([1, 2, 3])
b = np.zeros((2, 3))
c = np.ones(5)
d = np.arange(0, 10, 2)
e = np.linspace(0, 1, 5)

print('-'*22)
print(a)
print('-'*22)
print(b)
print('-'*22)
print(c)
print('-'*22)
print(d)
print('-'*35)
print(e)

----------------------
[1 2 3]
----------------------
[[0. 0. 0.]
 [0. 0. 0.]]
----------------------
[1. 1. 1. 1. 1.]
----------------------
[0 2 4 6 8]
-----------------------------------
[0.   0.25 0.5  0.75 1.  ]


### ndarray.shape and ndarray.reshape()
shape shows array dimensions, .reshape() changes the shape.

In [19]:
arr = np.arange(6)
print(arr)
print(arr.shape)         # (6,)
print(arr.reshape(2, 3)) # [[0 1 2]
                         #  [3 4 5]]

[0 1 2 3 4 5]
(6,)
[[0 1 2]
 [3 4 5]]


### element-wise operations

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)     # [5 7 9]
print(a * b)     # [ 4 10 18]
print(a ** 2)    # [1 4 9]

[5 7 9]
[ 4 10 18]
[1 4 9]
