# NUMPY
NumPy (Numerical Python) is a Python library for numerical computations. It provides an efficient array object (ndarray) and tools for mathematical, logical, shape manipulation, and statistical operations.

In [10]:
import numpy as np

In [11]:
arr = np.array([1, 2, 3, 4])
print(arr * 2)   # Vectorized operation → [2 4 6 8]

[2 4 6 8]


### Difference between a Python list and a NumPy array?

| Feature     | List                         | NumPy Array           |
|--------------|------------------------------|------------------------|
| Type         | Can hold different data types | Must hold same data type |
| Speed        | Slower                        | Faster (C-based)        |
| Memory       | More memory                   | Less memory             |
| Operations   | Loop-based                    | Vectorized              |


In [13]:
lst = [1, 2, 3]
arr = np.array([1, 2, 3])

print(lst * 2)  # [1, 2, 3, 1, 2, 3]
print(arr * 2)  # [2 4 6]

[1, 2, 3, 1, 2, 3]
[2 4 6]


### Create NumPy arrays

In [17]:
a = np.array([1, 2, 3])
b = np.zeros((2, 3))
c = np.ones(5)
d = np.arange(0, 10, 2)
e = np.linspace(0, 1, 5)

print('-'*22)
print(a)
print('-'*22)
print(b)
print('-'*22)
print(c)
print('-'*22)
print(d)
print('-'*35)
print(e)

----------------------
[1 2 3]
----------------------
[[0. 0. 0.]
 [0. 0. 0.]]
----------------------
[1. 1. 1. 1. 1.]
----------------------
[0 2 4 6 8]
-----------------------------------
[0.   0.25 0.5  0.75 1.  ]


### ndarray.shape and ndarray.reshape()
shape shows array dimensions, .reshape() changes the shape.

In [19]:
arr = np.arange(6)
print(arr)
print(arr.shape)         # (6,)
print(arr.reshape(2, 3)) # [[0 1 2]
                         #  [3 4 5]]

[0 1 2 3 4 5]
(6,)
[[0 1 2]
 [3 4 5]]


### element-wise operations

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)     # [5 7 9]
print(a * b)     # [ 4 10 18]
print(a ** b)    # [1 4 9]

[5 7 9]
[ 4 10 18]
[  1  32 729]


### Calculate statistical values
NumPy provides built-in methods like mean, std, sum, median.

In [24]:
arr = np.array([10, 20, 30, 40])

print(arr.mean(),'||', arr.std(),'||', arr.sum(),'||', np.median(arr))


25.0 || 11.180339887498949 || 100 || 25.0


# 📊 NumPy Statistical Methods

NumPy provides a wide range of statistical and mathematical methods for analyzing numerical data.

---

## 🧮 Basic Statistical Methods

| Function | Description |
|-----------|--------------|
| `np.mean(a)` | Mean (average) of array elements |
| `np.median(a)` | Median of array elements |
| `np.std(a)` | Standard deviation |
| `np.var(a)` | Variance |
| `np.sum(a)` | Sum of array elements |
| `np.prod(a)` | Product of array elements |
| `np.cumsum(a)` | Cumulative sum |
| `np.cumprod(a)` | Cumulative product |

---

## 📈 Min, Max, and Range

| Function | Description |
|-----------|--------------|
| `np.min(a)` | Minimum value |
| `np.max(a)` | Maximum value |
| `np.ptp(a)` | Range (max - min) |
| `np.argmin(a)` | Index of minimum value |
| `np.argmax(a)` | Index of maximum value |

---

## 📊 Percentiles and Quantiles

| Function | Description |
|-----------|--------------|
| `np.percentile(a, q)` | q-th percentile |
| `np.quantile(a, q)` | q-th quantile (fractional form) |

---

## ⚖️ Weighted & Average Calculations

| Function | Description |
|-----------|--------------|
| `np.average(a, weights=None)` | Weighted average |
| `np.mean(a, axis=None)` | Mean along specified axis |

---

## 🔢 Correlation and Covariance

| Function | Description |
|-----------|--------------|
| `np.corrcoef(a, b=None)` | Correlation coefficient matrix |
| `np.cov(a, b=None)` | Covariance matrix |

---

## 🧠 Other Useful Statistical Tools

| Function | Description |
|-----------|--------------|
| `np.histogram(a, bins)` | Histogram of data |
| `np.bincount(a)` | Count of occurrences of each integer value |
| `np.unique(a, return_counts=True)` | Unique values and counts |
| `np.nanmean(a)` | Mean ignoring NaNs |
| `np.nanstd(a)` | Std ignoring NaNs |
| `np.nansum(a)` | Sum ignoring NaNs |
| `np.nanmedian(a)` | Median ignoring NaNs |

---


### Handle missing values in NumPy

In [27]:
arr = np.array([1, 2, np.nan, 4])
print(np.nanmean(arr))  # Ignores NaN

print('-'*25)
print(arr)
print('-'*25)
arr[np.isnan(arr)] = np.nanmean(arr)
print(arr)
print('-'*25)


2.3333333333333335
-------------------------
[ 1.  2. nan  4.]
-------------------------
[1.         2.         2.33333333 4.        ]
-------------------------


### Matrix multiplication

In [26]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A @ B)


[[19 22]
 [43 50]]


### Unique elements and their counts

In [31]:
arr = np.array([1, 2, 2, 3, 3, 3])
print(np.unique(arr, return_counts=True))
print(np.unique(arr))

(array([1, 2, 3]), array([1, 2, 3]))
[1 2 3]


### Stack arrays vertically and horizontally
Use np.vstack() and np.hstack() to combine arrays.

In [32]:
a = np.array([1, 2])
b = np.array([3, 4])

print(np.vstack((a, b)))
print(np.hstack((a, b)))


[[1 2]
 [3 4]]
[1 2 3 4]
